pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

       stage('Build and Test') {
    steps {
        dir('java-cicd') {
            sh 'mvn clean package'
            sh 'mvn test'
            sh 'mvn deploy'
        }
    }
}

    stage('Docker Build') {
            steps {
        dir('java-cicd') {
            sh 'docker build -t java-cicd-demo:${BUILD_NUMBER} .'
        }
    }
    }
        

        stage('Docker Image Check') {
            steps {
               sh 'docker images java-cicd-demo:${BUILD_NUMBER}'
            }
        }
    }

    post {
        success {
            echo 'Build and Docker image creation successful!'
        }

        failure {
            echo 'Pipeline failed. Check the failed stage.'
        }
    }
}
