pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                dir('java-cicd') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('java-cicd') {
                    sh 'mvn test'
                }
            }
        }

    stage('Docker Build') {
            steps {
                sh 'docker build -t java-cicd-demo:${BUILD_NUMBER} .'
            }
        }

        stage('Docker Image Check') {
            steps {
                sh 'docker images java-cicd-demo'
            }
        }
    }

    post {
        success {
            echo 'Build and Docker image creation successful!'
        }

        failure {
            echo 'Pipeline failed. Check the failed stage.'
        }
    }
}
